#!/bin/bash

# Base script generated by NERSC Batch Script Generator on https://iris.nersc.gov/jobscript.html

#SBATCH -N 1
#SBATCH -C cpu
#SBATCH -q regular
#SBATCH -J hist
#SBATCH --mail-user=jessica_katz@berkeley.edu
#SBATCH --mail-type=ALL
#SBATCH -A m3298
#SBATCH -t 2:0:0

# OpenMP settings:
export OMP_NUM_THREADS=1
export OMP_PLACES=threads
export OMP_PROC_BIND=spread

#run the application:
module load python
srun -n 1 -c 256 --cpu_bind=none python parse_WRF_for_FIA_plots.py